base_url = "https://ryugibo.github.io/ueas"
title = "Unreal Engine Angelscript"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true

[extra]
logo = "angelscript_unreal.png"
